# Generated by Django 4.2.7 on 2023-11-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255)),
                ("userid", models.CharField(max_length=50)),
                ("action", models.CharField(max_length=50)),
            ],
        ),
    ]
