# Generated by Django 4.2.7 on 2023-11-24 19:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_chat_url_chat_vectorstore_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.CharField(max_length=50)),
                (
                    "chatid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("imgsrc", models.CharField(max_length=255)),
                ("url", models.CharField(default="", max_length=255)),
                ("vectorstore_path", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="chat",
            name="url",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="vectorstore_path",
        ),
        migrations.AlterField(
            model_name="chat",
            name="chatid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
