# Generated by Django 4.2.7 on 2023-11-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_thread_remove_chat_url_remove_chat_vectorstore_path_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.CharField(max_length=50)),
                ("email", models.CharField(default="", max_length=255, unique=True)),
                ("name", models.CharField(default="", max_length=255)),
                ("topics", models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
