# Generated by Django 4.2.7 on 2023-12-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_topic_alter_chat_message_alter_chat_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="topic",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
