# Generated by Django 4.2.7 on 2023-12-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_topic_generated_topic_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="budget_constraint_value",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="time_constraint_value",
        ),
        migrations.AddField(
            model_name="topic",
            name="cost_insight",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="topic",
            name="time_insight",
            field=models.JSONField(default=dict),
        ),
    ]
