# Generated by Django 4.2.7 on 2023-12-05 05:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_remove_topic_budget_constraint_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="chatid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
