# Generated by Django 4.2.7 on 2023-12-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_topic_chatid"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="visiondoctext",
            field=models.TextField(default=""),
        ),
    ]
