# Generated by Django 4.2.7 on 2023-12-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_topic_visiondoctext'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdoc',
            name='institution',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userdoc',
            name='jobtitle',
            field=models.CharField(default='', max_length=255),
        ),
    ]
