# Generated by Django 4.2.7 on 2023-12-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userdoc_institution_userdoc_jobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='market_insights',
            field=models.JSONField(default=dict),
        ),
    ]
