# Generated by Django 4.2.7 on 2023-12-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_topic_market_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdoc',
            name='bannerPic',
            field=models.TextField(default='https://www.eikojones.com/wp-content/uploads/2016/01/esperanza-inlet-sunrise-1080x480.jpg'),
        ),
        migrations.AddField(
            model_name='userdoc',
            name='college',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userdoc',
            name='currentplan',
            field=models.CharField(default='Free', max_length=7),
        ),
        migrations.AddField(
            model_name='userdoc',
            name='jobdescription',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userdoc',
            name='profilePic',
            field=models.TextField(default='https://images.unsplash.com/photo-1639605762180-c291953c008c?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=150&ixid=MnwxfDB8MXxyYW5kb218MHx8dXNlciwke3JhbmRvbVNlZWR9fHx8fHx8MTcwMjA0MTkzOQ&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=150'),
        ),
        migrations.AddField(
            model_name='userdoc',
            name='trumio',
            field=models.CharField(default='https://prod-app.trumio.ai/profile/TALENT/', max_length=255),
        ),
    ]
