# Generated by Django 4.2.7 on 2023-12-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_topic_market_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdoc',
            name='jobdescription',
            field=models.TextField(default=''),
        ),
    ]
