# Generated by Django 4.2.7 on 2023-12-08 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_userdoc_bannerpic_userdoc_college_and_more"),
        ("home", "0012_userdoc_jobdescription"),
    ]

    operations = []
