# Generated by Django 4.2.7 on 2023-12-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_merge_20231208_2134"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="similar_insights",
            field=models.TextField(default=""),
        ),
    ]
