# Generated by Django 4.2.7 on 2023-12-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_topic_similar_insights'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdoc',
            old_name='institution',
            new_name='company',
        ),
    ]
