# Generated by Django 4.2.7 on 2023-12-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_rename_college_userdoc_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="topicid",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together={("userid", "topicid")},
        ),
    ]
