# Generated by Django 4.2.7 on 2023-12-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_topic_topicid_alter_topic_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='market_insights',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
