# Generated by Django 4.2.7 on 2023-12-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_topic_topicid_alter_topic_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdoc',
            name='student_experience',
            field=models.JSONField(default=dict),
        ),
    ]
