# Generated by Django 4.2.7 on 2023-12-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_topic_market_insights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='cost_insight',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='time_insight',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
