# Generated by Django 4.2.7 on 2023-12-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_topic_cost_insight_alter_topic_time_insight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='similar_insights',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subtask',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='visiondoctext',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
