# Generated by Django 4.2.7 on 2023-12-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_userdoc_student_experience'),
        ('home', '0020_alter_topic_similar_insights_alter_topic_subtask_and_more'),
    ]

    operations = [
    ]
