# Generated by Django 4.2.7 on 2023-12-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_merge_20231213_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='skills',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
